# Title browser tab
browser_title: "Population tool - MapAction"
# Data scientists involved
data_scientists:
    "Daniele": "dcastellana@mapaction.org"
    "Piet": "pgerrits@mapaction.org"
    "Cate": "cseale@mapaction.org"
# Urls
url_data_science_wiki: "https://mapaction.atlassian.net/wiki/spaces/GAFO/overview"
url_project_wiki: "https://mapaction.atlassian.net/wiki/spaces/GAFO/pages/16280649751/Population+tool"
url_github_repo: "https://github.com/mapaction/population-tool"
# Layout and styles
# Sidebar
MA_logo_width: "60%"
MA_logo_background_position: "35% 10%"
sidebar_header: "Population tool"
sidebar_header_fontsize: "30px"
sidebar_header_fontweight: "bold"
about_box_background_color: "#dae7f4"
# Introduction and Documentation pages
docs_fontsize: "1.2rem"
docs_caption_fontsize: "1rem"
# Tool page
expander_header_fontsize: "23px"
widget_header_fontsize: "18px"
button_text_fontsize: "24px"
button_text_fontweight: "bold"
button_background_color: "#dae7f4"
